export const TEST = 'TEST'

// AUTHENTICATION

export const AUTH_METHOD_TOGGLE = 'AUTH_METHOD_TOGGLE';

export const AUTH_SENDAUTH_EXEC = 'AUTH_SENDAUTH_EXEC';
export const AUTH_GET_ACCESSKEYS = 'AUTH_GET_ACCESSKEYS';
export const AUTH_SET_ACCESSKEYS = 'AUTH_SET_ACCESSKEYS';
export const AUTH_CHECK_ACCESSKEYS = 'AUTH_CHECK_ACCESSKEYS';

export const AUTH_INPUT_UPDATED = 'AUTH_INPUT_UPDATED';
export const AUTH_TOTAL_VALIDITY = 'AUTH_TOTAL_VALIDITY';
export const AUTH_FAIL = 'AUTH_FAIL';



export const AUTH_SIGNIN_RESET = 'AUTH_SIGNIN_RESET';
export const AUTH_SIGNIN_ERROR = 'AUTH_SIGNIN_ERROR';

export const AUTH_SIGNUP = 'AUTH_SIGNUP';
export const AUTH_SIGNUP_ERROR = 'AUTH_SIGNUP_ERROR';
export const AUTH_SIGNUP_RESET = 'AUTH_SIGNUP_RESET';
export const AUTH_SIGNUP_SUCCESS = 'AUTH_SIGNUP_SUCCESS';
export const AUTH_TOGGLE_PROP = 'AUTH_TOGGLE_PROP';
export const AUTH_TOGGLE_ERROR = 'AUTH_TOGGLE_ERROR';

export const AUTH_RESET_UI = 'AUTH_RESET_UI';

// MAIN
export const MAIN_TEST = 'MAIN_TEST';

export const MAIN_SET_USER = 'MAIN_SET_USER';
export const MAIN_LOGGED_IN = "MAIN_LOGGED_IN";
export const MAIN_LOGIN_ERROR = "MAIN_LOGIN_ERROR";
export const MAIN_LOGOUT = 'MAIN_LOGOUT';
export const MAIN_TOGGLE_BACKGROUND = 'MAIN_TOGGLE_BACKGROUND';

export const MAIN_TOGGLE_AUTHINTRO = 'MAIN_TOGGLE_AUTHINTRO';


// CONTACT

export const CONTACT_INIT = 'CONTACT_INIT';
export const  CONTACT_RESET = 'CONTACT_RESET';
export const CONTACT_INPUT_UPDATED = 'CONTACT_INPUT_UPDATED';
export const CONTACT_TOTAL_VALIDITY = 'CONTACT_TOTAL_VALIDITY';
export const CONTACT_FORM_SUBMITTED = 'CONTACT_FORM_SUBMITTED';

// Skills
export const SKILLS_LOAD_PROGRESS = 'SKILLS_LOAD_PROGRESS';


//Cover Letter
export const COVERLETTER_LOADED = 'COVERLETTER_LOADED';
export const COVERLETTER_LOAD = 'COVERLETTER_LOAD';
export const COVERLETTER_SET_JOB = 'COVERLETTER_SET_JOB';
export const COVERLETTER_SET_CL = 'COVERLETTER_SET_CL';

